[package]
name = "seizou_count_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.9"  # または最新バージョン
tokio = { version = "1.34.0", features = ["full"] } # または最新バージョン
hyper = "0.14.13"
